# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vaibhav Gupta
title: Master's in Data Science Student at Vanderbilt University
email: vaibhav [dot] gupta [dot] 1 [at] vanderbilt [dot] edu

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: vaiibhavgupta
googlescholar_username: cH_BsHkAAAAJ
github_username:  vaiibhavgupta
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: medium
  icon: fab fa-medium
  url: https://medium.com/@vaiibhavgupta

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Vaibhav Gupta and I am second-year master's in data science student at Vanderbilt University. My research interests revolves around - <mark>Computer Vision</mark> and <mark>Explainable AI</mark>.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Vanderbilt University
        caption: 2023 - 2025
        sub_title: M.S. Data Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | 
          GPA: 3.89

          Relevant Coursework:
          - Probability and Statistical Inference
          - Time Series Analysis
          - Deep Learning
          - Natural Language Processing
          - Databases
          - Advanced Machine Learning
          - Reinforcement Learning
          - Big Data Scaling
          - Social Network Analysis
          - Generative AI
          - Data Science Algorithms

      - layout: left
        title: Thapar Institute of Engineering and Technology
        caption: 2016 - 2020
        sub_title: B.E. Electronics and Computer Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | 
          GPA: 3.52
          
          Relevant Coursework:
          - Computer Programming
          - Operating Systems
          - Data Structures and Algorithms
          - Database Management Systems
          - Computer Vision
          - Machine Learning
          - Numerical Analysis
          - Optimization Techniques
          - Graph Theory and Applications

  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Institute for Software Integrated Systems at Vanderbilt University
        # caption: May 2024 - 2025
        sub_title: Research Intern
        description: | 
        line 1
        line 2

      - layout: left
        title: AllianceBernstein
        # caption: May 2024 - 2025
        sub_title: Student Researcher
        description: | 
        line 1
        line 2

      - layout: left
        title: Nissan Motor Corporation
        # caption: May 2024 - 2025
        sub_title: Student Researcher
        description: | 
        line 1
        line 2

      - layout: left
        title: Language and Educational Analytics Research Lab at Vanderbilt University
        # caption: May 2024 - 2025
        sub_title: Research Assistant
        description: | 
        line 1
        line 2

  - title: Industry Experience
    layout: list
    content:
      - layout: left
        title: Deloitte
        caption: August 2020 - July 2023
        sub_title: Data Scientist
        description: | 
        • Architected and implemented a named-entity-recognition-based recommender engine with innovative and novel algorithms for acronym expansion, co-reference resolution, and relation extraction in Python using spaCy, PyTorch, and BERT models with processing time of under a second for 1000 tokens.
          o The finetuned named-entity-recognition models achieved a 95% F1-Score for six audit-related entities.
          o The co-reference resolution algorithm inferred 10x faster and was 90% more accurate than AllenNLP’s algorithm.
        • Designed and engineered an application in Python using Dash to orchestrate the development of the recommender system, train models, showcase data and models’ metrics, and provide a platform to prepare training data for fine-tuning language models.
        • Developed an NLP-based advanced clustering algorithm using Python, BERTs, spaCy, and HDBScan for automatic document review to significantly reduce manual efforts of auditors by over 70% and speed-up the document collection process by 75%.

      - layout: left
        title: Senvion India
        caption: January 2020 - June 2020
        sub_title: Data Engineer Intern
        description: | 
        • Crafted an end-to-end automated reporting pipeline using Cassandra, Python, and Apache Airflow to generate periodic performance reports to facilitate effective asset management. The pipeline processed data from the database and created visualizations, and generated Word documents, reducing report generation time by 70%.

        • Designed and established a Python-based robust pipeline to oversee the Extract, Transform, Load (ETL) process, incorporating quality assurance protocols to guarantee data integrity and reliability.

        • Developed automated tests using PyTest to guarantee data quality and consistency, reducing data errors by 20%.

      - layout: left
        title: JioVio Healthcare
        caption: June 2019 - July 2019
        sub_title: Computer Vision Engineer Intern
        description: | 
        • Developed a JavaScript application integrated with AWS Rekognition and AWS S3 to identify faces in over 10K images and 500 hours of video streaming from CCTV cameras.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
